name: "Update"
on:
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Nix"
        uses: determinatesystems/nix-installer-action@main
      - name: "Update"
        uses: determinatesystems/update-flake-lock@main
